### ISSUE TITLE
Weather does not show in the clock - GNOME 3.36.2

### ISSUE THREAD

**Issue by coxackie** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#10]
## Distro Name & Version
Arch Linux (rolling)

## GNOME Shell Version
3.36.2

## Other Installed Extensions
All other extensions disabled (see screenshot)

## Expected Behavior
Weather should show in the clock

## Current Behavior
Weather does not show in the clock

## Detailed Description
See screenshot - GNOME weather installed, location services on
![Screenshot from 2020-05-29 08-47-04](https://user-images.githubusercontent.com/22049642/83235126-51038c80-a189-11ea-9f5d-a0062d3b85a5.png)

**Comment by JasonLG1979** [comment]
The current weather is not shown in GNOME weather either. The extension gets it's weather info from GNOME Weather. You'll have to file a bug report with them.

**Comment by coxackie** [comment]
Hmm, OK, I can see that no data was pulled at that time, but it also does not show it when temperature data is there. Look at updated screenshots below. Apart from the "Unknown" condition (which I am not sure why it is there - is this the problem?), everything else seems to work fine with GNOME weather.

![Screenshot from 2020-05-30 07-49-26](https://user-images.githubusercontent.com/22049642/83321791-16adf400-a24a-11ea-9bf4-9a480d99aedd.png)

![Screenshot from 2020-05-30 07-44-46](https://user-images.githubusercontent.com/22049642/83321799-29282d80-a24a-11ea-93a1-67bb02f93915.png)

**Comment by coxackie** [comment]
A couple more screenshots, now without even "unknown" in condition:
![Screenshot from 2020-05-30 14-24-24](https://user-images.githubusercontent.com/22049642/83329443-7247a400-a281-11ea-8c8e-600965a63dd5.png)
![Screenshot from 2020-05-30 14-24-41](https://user-images.githubusercontent.com/22049642/83329446-74a9fe00-a281-11ea-8f74-33d6121b8b76.png)

**Comment by JasonLG1979** [comment]
Try turning off auto location and selecting a location manually. Being as though London is a big city I'm sure you'll have plenty of sources to choose from. I'm not sure how GNOME weather decides on the source of the info but not all sources are created equal.

**Comment by coxackie** [comment]
this actually worked... but wtf? gnome pick up an automatic location that is not part of the ones in the menu? there were only two local options to pick manually, and they both register for your extension.

**Comment by JasonLG1979** [comment]
> this actually worked... but wtf?

No idea. But it's always pretty much been the case that manually setting your location works better than auto location. My guess is that it just picks the closest source, which in my case is the Ankeny Regional Airport. Sounds legit until you see the Ankeny Regional Airport and realize that it's basically just field used by people with Cessnas and a couple of hangars. Ankeny being a suburb of the larger city of Des Moines I set my location to Des Moines for weather since it gets better results.
