### ISSUE TITLE
Temperature is displayed in F (irrespective of Gnome-weather settings)

### ISSUE THREAD

**Issue by gauvins2** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#13]
## Distro Name & Version
Pop!_OS 20.04 64bit / Linux 5.4.0-7642-generic
## GNOME Shell Version
3.36.3
## Other Installed Extensions

alt-tab: raise first window
dash to panel
weather in the clock
[all other extensions are off]
## Expected Behavior

GNOME weather temperature unit should reflect in the extension
## Current Behavior

weather is always displayed in F degrees
## Detailed Description

probably not necessary :)

**Comment by JasonLG1979** [comment]
Yep. I can confirm. I'll have to dig into it to see what the issue is. the extension doesn't decide the units, maybe it's going off you system locale settings?

**Comment by gauvins2** [comment]
thanks for your time.

hmmm... will try that (you are right -- my locale was set to United States.
Usually what I prefer but, true, I prefer the metric system. Have changed
the setting and will reboot when convenient. Will let you know how things
turn out.

take care

**Comment by gauvins2** [comment]
Hello again

changed locale, reboot and temperature is now displayed in Celsius.

take care

Stephane
