### ISSUE TITLE
Indicator not visible on additional monitors

### ISSUE THREAD

**Issue by qoheniac** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#14]
## Distro Name & Version
Fedora 32

## GNOME Shell Version
3.36.6

## Other Installed Extensions

- AppIndicator and KStatusNotifierItem Support
- Background Logo
- Dash to Dock
- Extensions Sync
- Mailnag
- Multi Monitors Add-On
- Sound Input & Output Device Chooser
- TopIcons Plus

## Expected Behavior
I see Weather In The Clock on all monitors.

## Current Behavior
I only see Weather In The Clock on my primary monitor.

## Detailed Description
It would be completely satisfactory for me if I could use the [Multi Monitors Add-On](https://github.com/spin83/multi-monitors-add-on) to add the Weather In The Clock indicator for transfer to additional monitors like it's possible for e. g. the [Extensions Sync](https://github.com/oae/gnome-shell-extensions-sync) icon or the [Places Status Indicator](https://gitlab.gnome.org/GNOME/gnome-shell-extensions).

**Comment by JasonLG1979** [comment]
I only have one monitor I have no way to test. Do you have multiple notification/calendar menus? I'm not even sure how the GNOME panel behaves with multiple monitors?

**Comment by JasonLG1979** [comment]
This extension is not an indicator button. It embeds the weather info into the notification menu button.

**Comment by qoheniac** [comment]
Interesting, normally GNOME doesn't show the clock (i. e. the notification menu button ?) on every monitor (actually it shows the whole panel only on the primary monitor) but the Multi Monitors Add-On has an option to show the panel on every monitor and you can further adjust what to show on these additional panels. One option here is "Show DateTime-Button on additional monitors". If this is activated the clock shows up on additional monitors but without the weather information from your extension.

**Comment by qoheniac** [comment]
Ok, looking [here](https://github.com/spin83/multi-monitors-add-on/blob/master/multi-monitors-add-on%40spin83/mmcalendar.js) it seems like they somewhat reimplemented the panel clock. I also noticed that if I click on the clock on one of the additional monitors it shows a drop down info box very similar to that on the primary monitor but some notifications are only shown on the primary monitor and the calendar is there but the weather and world clock feature are missing. I assumed the clock was just a copy of that on the primary monitor but it isn't. So, I think I should open an issue at the Multi Monitors Add-On repository.
