### ISSUE TITLE
GNOME Shell 40

### ISSUE THREAD

**Issue by luca-viggiani** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#15]
Can you make it compatible with GS 40 please?

**Comment by JasonLG1979** [comment]
Sure. I'll give it a test run on Fedora 34 and make sure it works. It's probably just a matter of a version bump. If you install it manually does it work?

**Comment by luca-viggiani** [comment]
Honestly I haven't tried as, by reading the migrating guide, it says you need to use gtk-4 rather than gtk-3. Hopefully it's just a matter of adding the proper version to the manifest or so

**Comment by JasonLG1979** [comment]
It doesn't use any GTK widgets I don't think it that really matters, all gnome-shell-extension-mpris-indicator-button required to work was a version bump in the metadata.json.

**Comment by JasonLG1979** [comment]
That reminds me I need to bump the version in that from 40.beta to 40...

**Comment by JasonLG1979** [comment]
Yep. Just tested it out in Boxes on Fedora 34. All it needs is a version bump. It's still got the styling issue mentioned in #8 I haven't figured out how to fix that yet.

**Comment by JasonLG1979** [comment]
I'll push an update to the extension site tomorrow.

**Comment by luca-viggiani** [comment]
Great thank you! #8 is something I can live with! :)

**Comment by JasonLG1979** [comment]
It really should be default in the shell to have the weather info in the panel IMHO.

**Comment by luca-viggiani** [comment]
> It really should be default in the shell to have the weather info in the panel IMHO.

agree

**Comment by JasonLG1979** [comment]
I just uploaded it and the update is live now. It must have auto approved since it's just a version bump.
