### ISSUE TITLE
Temperature Unit Font/Symbol

### ISSUE THREAD

**Issue by qoheniac** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#18]
Probably not an issue with this extension in particular but just a somehow related question I have and maybe someone here knows an answer. Take a look at the example screenshot `data/Screenshot.png`, i. e. this one:
![data/Screenshot.png](https://raw.githubusercontent.com/JasonLG1979/gnome-shell-extension-weather-in-the-clock/master/data/Screenshot.png)
The F at the beginning of Feb looks different than the Fahrenheit F. Is this a different font or a different symbol and how do I find out? Can I change that? To me the Celsius C looks a bit ugly especially in combination with the Clear Sans font which I use as system font. This is how it looks for me:
![date, time and weather](https://user-images.githubusercontent.com/29815186/123439785-5fadb480-d5d2-11eb-88a4-0e2df5726a2f.png)
The C is larger than the other letters which doesn't look very well, IMHO.

**Comment by qoheniac** [comment]
Comparing my issue to [this one](https://github.com/JasonLG1979/gnome-shell-extension-weather-in-the-clock/issues/17) I came to the conclusion that this is probably a symbol as well as an font issue. The temperature unit is probably Unicode U+2109 (degree Fahrenheit) or U+2103 (degree Celsius) so that the Fahrenheit F and the one in Feb are not the same symbol. However, those Unicode symbols are included in both Clear Sans (my system font) and Cantarell (default system font and my fallback) and both look different from what I see in the top bar. Unfortunately, I have no idea what font is used there, why, and how I can change it.

**Comment by JasonLG1979** [comment]
I still don't know what font is used for the temperature unit symbol in the top bar. I don't specify a font so it will use whatever font you're Shell theme is configured to use. I don't even manipulate the message in any way other than replacing `"--"` with `""`.  As `"--"` is what the weather returns if there is no information and we don't want that in the panel. I get the message straight from the same place as the calendar get's it's info.

  https://github.com/JasonLG1979/gnome-shell-extension-weather-in-the-clock/blob/master/weatherintheclock%40JasonLG1979.github.io/extension.js#L29
  
  https://github.com/JasonLG1979/gnome-shell-extension-weather-in-the-clock/blob/master/weatherintheclock%40JasonLG1979.github.io/extension.js#L98

**Comment by qoheniac** [comment]
Looking at [this function](https://gitlab.gnome.org/GNOME/libgweather/-/blob/master/libgweather/gweather-weather.c#L922) it seems link those Unicode symbols are just appended to the numbers so they probably use the same font so for me the symbol must be in DejaVu Sans as that is the first fallback that has the symbol. It does not really look like DejaVu Sans. Anyways, Latin Modern Sans has the symbol too and it fits the style of Clear Sans a bit better. So I move Latin Modern Sans in front of DejaVu Sans in my `~/.fonts.conf` like this
```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>

  <alias binding="strong">
    <family>Clear Sans</family>
    <prefer>
      <family>Clear Sans</family>
      <family>Cantarell</family>
      <family>Latin Modern Sans</family>
      <family>DejaVu Sans</family>
    </prefer>
  </alias>

</fontconfig>
```
and now it looks a bit better.
![weather](https://user-images.githubusercontent.com/29815186/123446027-c33ae080-d5d8-11eb-9793-1a14c8335961.png)
I guess I can live with this and it's not an issue with this extension so I'm closing this here. Thanks for your reply!
