### ISSUE TITLE
Open gnome-weather upon clicking on the topbar icon

### ISSUE THREAD

**Issue by pacho2** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#19]
Hello,

It would be nice if clicking on the weather icon would open directly gnome-weather app

Thanks

## Distro Name & Version
Gentoo

## GNOME Shell Version
40.4

**Comment by JasonLG1979** [comment]
The weather info is embedded in the button that toggles the calendar/notifications menu. It's not a separate button. You can very easily just click the weather section of that menu to open gnome-weather.
