### ISSUE TITLE
Gnome 41 Support

### ISSUE THREAD

**Issue by RistrettoMike** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#22]
This extension appears to work properly on Gnome 41 by changing shell version "40" to "41" in metadata.json :)

**Comment by P-IH** [comment]
Thanks, worked fine.

**Comment by scottbeamer** [comment]
Not working for me in GNOME 41.

**Comment by scottbeamer** [comment]
> This extension appears to work properly on Gnome 41 by changing shell version "40" to "41" in metadata.json :)

How do I do that?

**Comment by JasonLG1979** [comment]
Sorry for the late reply. It works in that in functions but they changed some things that make it not look the greatest. I added support for 41 and will upload an update shortly.
