### ISSUE TITLE
Still can’t be installed from `extensions.gnome.org` to GNOME 41

### ISSUE THREAD

**Issue by ai** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#25]
## Distro Name & Version

Fedora 35

## GNOME Shell Version

GNOME 41

## Expected Behavior

See `On`/`Off` switcher

## Current Behavior

![Снимок экрана от 2021-11-15 12-20-54](https://user-images.githubusercontent.com/19343/141773493-ba78f405-34b1-4673-9052-35e571afa84b.png)

**Comment by lapsha38** [comment]
u also can do something like this:

> cd /tmp
> git clone https://github.com/JasonLG1979/gnome-shell-extension-weather-in-the-clock/
> cp -r gnome-shell-extension-weather-in-the-clock/weatherintheclock@JasonLG1979.github.io /home/$user/.local/share/gnome-shell/extensions/

after reboot all gonna be alright

**Comment by thmo** [comment]
Manually updating worked for me.

Maybe the automatic update doesn't work because of a missing 'version' field in the `metadata.json`?

**Comment by LoneFenris** [comment]
As near as I can tell, the updated extension was either never uploaded to e.g.o or never approved by them.

**Comment by Th0rleif** [comment]
> u also can do something like this:
> 
> > cd /tmp
> > git clone https://github.com/JasonLG1979/gnome-shell-extension-weather-in-the-clock/
> > cp -r gnome-shell-extension-weather-in-the-clock/weatherintheclock@JasonLG1979.github.io /home/$user/.local/share/gnome-shell/extensions/
> 
> after reboot all gonna be alright

Reboot should not be necessary, simply logout then login.

**Comment by Th0rleif** [comment]
As an ad-hoc solution (waiting for the update), one can easily edit `${HOME}/.local/share/gnome-shell/extensions/weatherintheclock@JasonLG1979.github.io/metadata.json` add `"41"` to the version list as follow:
```json
  "shell-version": [
    "3.38",
    "40",
    "41"
  ],
```

**Comment by ironbone** [comment]
Gonme 41.2 the manualy way does not work

**Comment by lapsha38** [comment]
> 

i can install it today manualy in fedora 35. maybe u do something wrong?

**Comment by ironbone** [comment]
Sorry - after updating the system - it works

**Comment by f1lipe** [comment]
Hello, I just manually installed and it is working fine in Gnome 41. 

Is there any reason why support for Gnome 41 is not available in extensions.gnome.org yet? Was it submitted by @JasonLG1979?

This is a very useful extension and works just fine.

Thanks!

**Comment by JasonLG1979** [comment]
It's more than just charging metadata.json to include 41. I haven't updated the extension because I'm not happy with how it functions (or rather doesn't sometimes) or looks these days. I really do not have the time nor the desire bring fix these issues and I'm really not even sure that you can? Basically unless someone else steps up this extension is effectively dead.
