### ISSUE TITLE
Gnome 42 support

### ISSUE THREAD

**Issue by pacho2** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#26]
metadata.json will need to be updated

Thanks!

**Comment by chmouel** [comment]
there is already a weather in the clock in gnome 42 isnt it ?

![image](https://user-images.githubusercontent.com/98980/162389611-ac92e702-54fb-48c2-bee5-f16185a9d9df.png)

**Comment by pacho2** [comment]
This extension adds the icon to the top bar next to the clock

**Comment by rr1231234** [comment]
please update

ubuntu 22.4, gnome 42

**Comment by jumpnett** [comment]
It looks like the shell version has been updated in [github](https://github.com/JasonLG1979/gnome-shell-extension-weather-in-the-clock/blob/4c8dbc0831515e1b22d9b37601e83cebc2cc127d/weatherintheclock@JasonLG1979.github.io/metadata.json), but not on the [gnome extensions page](https://extensions.gnome.org/extension/1380/weather-in-the-clock/): 
![image](https://user-images.githubusercontent.com/1007279/180061415-b877ff6b-8299-489c-9da1-7d64004d68ff.png)

**Comment by LuciousLisa** [comment]
@JasonLG1979 Please push the Gnome 42 version to the Gnome Extensions repo too. I miss having your extension installed and hate having to actually look outside to see the weather! :wink:

**Comment by carrot69** [comment]
Until this is updated into the Gnome Extensions website, you can install it in gnome 42 by doing it manually: https://github.com/JasonLG1979/gnome-shell-extension-weather-in-the-clock/wiki/Installation
