### ISSUE TITLE
Weather update moves panel items around briefly

### ISSUE THREAD

**Issue by chrisjbillington** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#4]
This is just a nitpick, but it would be nice if the weather info did not disappear whilst updating the weather. It would be nice if it stayed displayed right until the new weather info replaced it.

By blanking it out for a second during an update, other panel items near it move around, and there's a visible motion of items in the panel as it disappears and reappears a second later with the new weather info. It would be nicer if the info could update in-place so it is not distracting, only disappearing if the update fails or something like that.

This is more obvious for me than in a default setup, because I am using Frippery Move Clock to move the clock to the right, so there are a number of panel items near the clock that all move around when the space is temporarily freed up in the panel during an update.

## Distro Name & Version
 Arch Linux, fully updated

## GNOME Shell Version
3.30.2

## Other Installed Extensions
* Launch new instance
* AlternateTab
* User Themes
* Frippery Move Clock
* Impatience
* (K)StatusNotifierItem/AppIndicator Support
* Transparent OSD
* Arch Linux Updates Indicator
* Bumblebee Status
* Status Area Horizontal Spacing
* system-monitor
* NoAnnoyance
* Panel OSD

## Expected Behavior
For the weather to update in-place keeping the panel item approximately the same width.

## Current Behavior
The panel item disappears for about a second whilst the weather info is updated, resulting in other panel items moving to fill the gap.

**Comment by whnr** [comment]
So subtle yet so noticeable!

**Comment by JasonLG1979** [comment]
There's nothing I can really do about it.
