### ISSUE TITLE
Weather is not available 

### ISSUE THREAD

**Issue by Mladia** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#5]
## Distro Name & Version
5.0.9-arch1-1-ARCH

## GNOME Shell Version
3.32.1

## Other Installed Extensions
Auto Move Windows
Native Window Placement
Removable Drive Menu
Screenshot Window Sizer
Drop Down Terminal X
MConnect
TopIcons Plus
windowNavigator
Wallpaper Changer
Panel OSD
Activities Configurator
User Themes
AlternateTab
Multi Monitors Add-On
Caffeine
Hibernate Status Button
Impatience
Dash to Dock

## Expected Behavior
To correctly show the weather

## Current Behavior
Constantly showing "Weather information is currently not available" or "Loading". 

## Detailed Description
Upon clicking on it, the GNOME Weather app opens and weather information is properly shown there

**Comment by JasonLG1979** [comment]
GNOME Weather is required for this extension to work.

Your "Current Behavior" indicates that you are referring to the default GNOME weather info. 

I think you are confusing what this extension does. It does not add, nor does it have anything to do with the weather info shown under the calendar in the date/time menu (notification area) other than they both get their info from the same place. The weather info under the calendar in the date/time menu (notification area) is there by default in GNOME Shell.

What this extension does is add a weather condition icon and temp to the panel next to the date/time. If there is no weather info available it will be hidden.

**Comment by JasonLG1979** [comment]
![Stuff](https://user-images.githubusercontent.com/6667703/56753008-3a516180-674f-11e9-8a91-3faf26dc3194.png)

**Comment by Mladia** [comment]
All right, I see. It does not seem work this way at all and I am not seeing anything right of the clock, but in my case it does not matter, since it is not what I am looking for. 
Thank you for your time and explanation, Jason. If nobody else has the same problem, this Issue could be closed.

**Comment by JasonLG1979** [comment]
@Mladia GNOME Weather is basically your control point for both my extension and the Weather info under the calendar. In my experience on my desktop computer it works best to disable "Automatic Location" and manually search for your location.
![Screenshot from 2019-04-26 09-47-11](https://user-images.githubusercontent.com/6667703/56816192-a348e000-6808-11e9-8c78-f70f166b73e2.png)

**Comment by Mladia** [comment]
Turning off Automatic Location solved all the issues. 
Now I see properly the "Weather in the clock" extension and the weather when you open the clock. Thanks a lot!
