### ISSUE TITLE
add 3.36 to shell-version in metada.json

### ISSUE THREAD

**Issue by maogouste** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#7]
I konw, I should put lots of details here. 

But, I think the title of it should be enough.

I'm using the beta of ubuntu 20.04 and your beautiful extension went missing as soon as they updated the gnome shell to 3.36

**Comment by JasonLG1979** [comment]
Sure. Can do.

**Comment by maogouste** [comment]
thanks
