### ISSUE TITLE
Weather icon not highlighted when clock is clicked

### ISSUE THREAD

**Issue by shbach** [JasonLG1979/gnome-shell-extension-weather-in-the-clock#8]
## Distro Name & Version
Solus 4.1

## GNOME Shell Version 
3.36

## Other Installed Extensions

All other extensions were disabled and this still occurred.

## Expected Behavior

The weather icon should also be highlighted when clicking as was ![previously](https://github.com/JasonLG1979/gnome-shell-extensions-weather-in-the-clock/blob/master/data/Screenshot.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/5298745/78293953-553f6080-74de-11ea-9222-771c94be4c78.png)

**Comment by JasonLG1979** [comment]
I noticed that myself. I'm sure it's just a style class issue. I'll have to see what's changed in 3.36 this weekend when I get some time.

**Comment by sheeepdev** [comment]
I'm having this same issue now. I recently updated my GNOME shell theme and it started happening, but the problem is even happening without the theme applied for some wierd reason.
